namespace: AMA

collections:
  themes:
    # whatever stored as keywords on the image's metadata
    - name: FL20
      category: Focal Length
    - name: FL28
      category: Focal Length
    - name: FL35
      category: Focal Length
    - name: FL37
      category: Focal Length
    - name: FL42
      category: Focal Length
    - name: FL45
      category: Focal Length
    - name: FL50
      category: Focal Length
    - name: FL58
      category: Focal Length
    - name: FL60
      category: Focal Length
    - name: FL67
      category: Focal Length
    - name: FL75
      category: Focal Length
    - name: FL85
      category: Focal Length
    - name: Architecture
      category: Urban
    - name: Blur
      category: Urban
    - name: CameraMode-APSCMode
      category: Urban
    - name: Cinemoments
      category: Urban
    - name: Coffee
      category: Urban
    - name: Collectables
      category: Urban
    - name: Cyberpunk
      category: Urban
    - name: Food
      category: Urban
    - name: Hike
      category: Urban
    - name: Historical
      category: Urban
    - name: Isolation
      category: Urban
    - name: Kitched
      category: Urban
    - name: MultiColors
      category: Urban
    - name: Night
      category: Urban
    - name: Palm Trees
      category: Urban
    - name: Panning
      category: Urban
    - name: Port
      category: Urban
    - name: Series
      category: Urban
    - name: Street
      category: Urban
    - name: Sunrise
      category: Urban
    - name: Sunset
      category: Urban
    - name: Tourism
      category: Urban
    - name: Unknown
      category: Urban
    - name: Urban
      category: Urban
    - name: Urban Landscape
      category: Urban
    - name: VerticalLandscape
      category: Urban
    - name: View
      category: Urban

  definitions:
    # CAMERAS + FILE_FORMAT
    - name: Sony 7ii + JPEG
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: Sony ILCE-7M2
        fileFormat:
          criteria: fileFormat
          operation: '=='
          value: JPEG

    - name: Sony 7Cii + JPEG
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: Sony ILCE-7CM2
        fileFormat:
          criteria: fileFormat
          operation: '=='
          value: JPEG

    - name: Sony 7ii + RAW
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: Sony ILCE-7M2
        fileFormat:
          criteria: fileFormat
          operation: '=='
          value: RAW

    - name: Sony 7Cii + RAW
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: Sony ILCE-7CM2
        fileFormat:
          criteria: fileFormat
          operation: '=='
          value: RAW

    - name: iPhone
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: iphone

    # PHASES
    - name: review required
      prefix: 'phase'
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: '=='
          value: 0
        labelColor:
          criteria: labelColor
          operation: '=='
          value: 1

    - name: export ready
      prefix: 'phase'
      combineType: intersect
      config:
        rating:
          criteria: rating
          operation: '>='
          value: 3
        labelColor:
          criteria: labelColor
          operation: '=='
          value: 3

    - name: unmarked
      prefix: 'phase'
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: '=='
          value: 0

    - name: marked for deletion
      prefix: 'phase'
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: '=='
          value: -1

    - name: WIP
      prefix: 'phase'
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: '=='
          value: 1
        labelColor:
          criteria: labelColor
          operation: '=='
          value: 4

    # LENSES
    - name: Tamron 28-75mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: E 28-75mm F2.8-2.8

    - name: Tamron 20mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: E 20mm F2.8 F050

    - name: Samyang AF 45mm F1.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: SAMYANG AF 45mm F1.8

    - name: Mir-1B 37mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Mir-1B 37mm F2.8

    - name: Jupiter-9 85mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Jupiter-9 85mm F2

    - name: Jupiter-8 50mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Jupiter-8 50mm F2

    - name: Industar 26m 52mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Industar 26m 52mm F2.8

    - name: Helios 44M-4 MC 58mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Helios 44M-4 MC 58mm F2

    - name: Helios 44M-4 58mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Helios 44M-4 58mm F2

    - name: Helios 44-2 58mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Helios 44-2 58mm F2

    - name: Canon LTM 50mm F1.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Canon LTM 50mm F1.8

    - name: Canon FD 50mm F1.4
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Canon FD 50mm F1.4

    - name: Canon FD 50mm F1.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Canon FD 50mm F1.8

    - name: Canon FD 35mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Canon FD 35mm F2.8

    - name: Auto-Beroflex 28mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Auto-Beroflex 28mm F2.8
