namespace: AMA

collections:
  themes:
    - Multicolor
    - Night
    - Street
    - Urban
    - Palm Trees
    - Sunrise
    - Sunset
    - FL20
    - FL28
    - FL35
    - FL37
    - FL42
    - FL45
    - FL50
    - FL58
    - FL75
    - FL85

  definitions:
    - name: Tamron 28-75mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: E 28-75mm F2.8-2.8

    - name: Tamron 20mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: E 20mm F2.8 F050

    - name: SAMYANG AF 45mm F1.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: SAMYANG AF 45mm F1.8

    - name: Mir-1B 37mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Mir-1B 37mm F2.8

    - name: Jupiter-9 85mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Jupiter-9 85mm F2

    - name: Jupiter-8 50mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Jupiter-8 50mm F2

    - name: Industar 26m 52mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Industar 26m 52mm F2.8

    - name: Helios 44M-4 MC 58mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Helios 44M-4 MC 58mm F2

    - name: Helios 44M-4 58mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Helios 44M-4 58mm F2

    - name: Helios 44-2 58mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Helios 44-2 58mm F2

    - name: Canon LTM 50mm F1.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Canon LTM 50mm F1.8

    - name: Canon FD 50mm F1.4
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Canon FD 50mm F1.4

    - name: Canon FD 50mm F1.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Canon FD 50mm F1.8

    - name: Canon FD 35mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Canon FD 35mm F2.8

    - name: Auto-Beroflex 28mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: "=="
          value: Auto-Beroflex 28mm F2.8

    - name: review required
      prefix: "phase"
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: "=="
          value: 0
        labelColor:
          criteria: labelColor
          operation: ">="
          value: 1

    - name: export ready
      prefix: "phase"
      combineType: intersect
      config:
        rating:
          criteria: rating
          operation: ">="
          value: 3
        labelColor:
          criteria: labelColor
          operation: ">="
          value: 3

    - name: unmarked
      prefix: "phase"
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: "=="
          value: 0

    - name: marked for deletion
      prefix: "phase"
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: "=="
          value: -1

    - name: WIP
      prefix: "phase"
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: "=="
          value: 1
        labelColor:
          criteria: labelColor
          operation: "=="
          value: 4
