namespace: AMA

collections:
  themes:
    # whatever stored as keywords on the image's metadata
    - FL20
    - FL28
    - FL35
    - FL37
    - FL42
    - FL45
    - FL50
    - FL58
    - FL60
    - FL67
    - FL75
    - FL85
    - Architecture
    - Blur
    - CameraMode-APSCMode
    - Cinemoments
    - Coffee
    - Collectables
    - Cyberpunk
    - Food
    - Hike
    - Historical
    - Isolation
    - Kitched
    - MultiColors
    - Night
    - Palm Trees
    - Panning
    - Port
    - Series
    - Street
    - Sunrise
    - Sunset
    - Tourism
    - Unknown
    - Urban
    - Urban Landscape
    - VerticalLandscape
    - View

  definitions:
    # CAMERAS + FILE_FORMAT
    - name: Sony 7ii + JPEG
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: Sony ILCE-7M2
        fileFormat:
          criteria: fileFormat
          operation: '=='
          value: JPEG

    - name: Sony 7Cii + JPEG
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: Sony ILCE-7CM2
        fileFormat:
          criteria: fileFormat
          operation: '=='
          value: JPEG

    - name: Sony 7ii + RAW
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: Sony ILCE-7M2
        fileFormat:
          criteria: fileFormat
          operation: '=='
          value: RAW

    - name: Sony 7Cii + RAW
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: Sony ILCE-7CM2
        fileFormat:
          criteria: fileFormat
          operation: '=='
          value: RAW

    - name: iPhone
      prefix: 'camera'
      combineType: intersect
      config:
        pick:
          criteria: camera
          operation: any
          value: iphone

    # PHASES
    - name: review required
      prefix: 'phase'
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: '=='
          value: 0
        labelColor:
          criteria: labelColor
          operation: '=='
          value: 1

    - name: export ready
      prefix: 'phase'
      combineType: intersect
      config:
        rating:
          criteria: rating
          operation: '>='
          value: 3
        labelColor:
          criteria: labelColor
          operation: '=='
          value: 3

    - name: unmarked
      prefix: 'phase'
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: '=='
          value: 0

    - name: marked for deletion
      prefix: 'phase'
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: '=='
          value: -1

    - name: WIP
      prefix: 'phase'
      combineType: intersect
      config:
        pick:
          criteria: pick
          operation: '=='
          value: 1
        labelColor:
          criteria: labelColor
          operation: '=='
          value: 4

    # LENSES
    - name: Tamron 28-75mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: E 28-75mm F2.8-2.8

    - name: Tamron 20mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: E 20mm F2.8 F050

    - name: Samyang AF 45mm F1.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: SAMYANG AF 45mm F1.8

    - name: Mir-1B 37mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Mir-1B 37mm F2.8

    - name: Jupiter-9 85mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Jupiter-9 85mm F2

    - name: Jupiter-8 50mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Jupiter-8 50mm F2

    - name: Industar 26m 52mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Industar 26m 52mm F2.8

    - name: Helios 44M-4 MC 58mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Helios 44M-4 MC 58mm F2

    - name: Helios 44M-4 58mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Helios 44M-4 58mm F2

    - name: Helios 44-2 58mm F2
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Helios 44-2 58mm F2

    - name: Canon LTM 50mm F1.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Canon LTM 50mm F1.8

    - name: Canon FD 50mm F1.4
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Canon FD 50mm F1.4

    - name: Canon FD 50mm F1.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Canon FD 50mm F1.8

    - name: Canon FD 35mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Canon FD 35mm F2.8

    - name: Auto-Beroflex 28mm F2.8
      prefix: lens
      combineType: intersect
      config:
        lens:
          criteria: lens
          operation: '=='
          value: Auto-Beroflex 28mm F2.8
